#!/bin/sh

#lang=chi
lang=eng
for doc in $(cut -d' ' -f1 catalog_$lang.txt); do 
  for year in {2006..2015}; do 

    [ ! -d by_catalog/$doc ] && mkdir -p $lang/by_catalog/$doc 
    [ ! -d by_year/$year ]   && mkdir -p $lang/by_year/$year
    
    fileName="${doc}_${lang}_$year.pdf"
    filePath="pdf/$fileName"

    ## download only if not downloaded 
    [ ! -f $filePath ] && curl http://www.budget.gov.hk/$year/$lang/pdf/$doc.pdf > $filePath
    
    ## symlink
    ln -fs ../../../$filePath $lang/by_year/$year/$fileName
    ln -fs ../../../$filePath $lang/by_catalog/$doc/$fileName
  done 
done
